### PR TITLE
Chore(ignore): add git

### PR DESCRIPTION
**Pull request by AugustinMauroy**
https://github.com/nodejs/next-10/blob/e1f2042b0aca14add92cd6907e80e0237e8d98f1/surveys/.DS_Store

### CODE REVIEW

**Comment by mhdawson** [comment]
@AugustinMauroy I need more context to be able to understand the what/why for this PR.

**Comment by AugustinMauroy** [comment]
I don't know when but we had pushed an `.DS_store` it's an unix file(binary).
So we should put in ignore.

**Comment by wesleytodd** [comment]
Here is the file: https://github.com/nodejs/next-10/blob/main/surveys/.DS_Store

**Comment by AugustinMauroy** [comment]
it's an other unix file

**Comment by wesleytodd** [comment]
It is a cert file as part of making an ssl cert, and I have no idea why anyone would commit those. I dont like having this in the `.gitignore` unless something in this repo clearly needed it, which I don't think it does.

**Pull request closed without merging**
